package com.food.kuruyia.foodretriever.utils;

public enum DataType {
    DATA_SCHEDULE_START,
    DATA_SCHEDULE_ADD,
    DATA_SCHEDULE_REMOVE,
    DATA_SCHEDULE_ENABLE,
    DATA_SCHEDULE_DATE,
    DATA_SCHEDULE_RATIO,
    DATA_SCHEDULE_END,

    DATA_DOG_START,
    DATA_DOG_NAME,
    DATA_DOG_WEIGHT,
    DATA_DOG_REGULATION_ENABLE,
    DATA_DOG_REGULATION_VALUE,
    DATA_DOG_END,
}
